# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @plugin 'laktak/extrakto'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'Morantron/tmux-fingers'

set -g @catppuccin_flavor 'latte' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
